#!/bin/bash
# Synchronize tracked HarmonyOS source mirrors into the generated hvigor project.
#
# The hvigor project under build/libstellarium-harmonyos is not tracked by Git,
# but it is what assembleHap actually compiles. After rollbacks or agent edits,
# stale generated files can survive there and make Git look clean while the HAP
# still contains old native/ArkUI code.
#
# This script mirrors whole source trees instead of an explicit file list. The
# previous explicit list silently missed 34 media icons and 34 ArkTS modules
# (QChildProcess, QtUtils, ic_globe, ic_refresh, ...), which made the generated
# project fail to compile even though Git looked clean. Keep directory mirrors
# so a newly referenced resource or module is always carried over.
#
# Precedence (later wins on conflicting paths):
#   1. harmonyos/ets-source/**            -> entry/src/main/ets/**
#   2. harmonyos/ets-source/resources/**  -> entry/src/main/resources/**
#   3. harmonyos/resources/**             -> entry/src/main/resources/**   (module resources win)
#   4. harmonyos/AppScope/**              -> AppScope/**
#   5. harmonyos/module.json5             -> entry/src/main/module.json5
#   6. harmonyos/cpp-source/**            -> entry/src/main/cpp/**

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

GEN_ROOT="$REPO_ROOT/build/libstellarium-harmonyos"
MODULE_ROOT="$GEN_ROOT/entry/src/main"

# The Qt platform patch is generated by build-ohos-platform-patch.sh from the
# Qt for OHOS tree. It is a separate pipeline from the ArkTS/resource mirror, so
# a machine that has not built Qt yet must still be able to sync source mirrors.
if [ -f "$REPO_ROOT/build/qt-platform-patch/manifest.json" ]; then
  node "$SCRIPT_DIR/check-ohos-platform-patch.mjs" --sync
else
  echo "WARNING: build/qt-platform-patch/manifest.json is missing; skipping Qt platform patch sync." >&2
  echo "         Run scripts/build-ohos-platform-patch.sh before packaging native Qt content." >&2
fi

if [ ! -d "$MODULE_ROOT/ets" ]; then
  echo "ERROR: missing hvigor destination project: $MODULE_ROOT/ets" >&2
  echo "Open/generate the HarmonyOS build project at build/libstellarium-harmonyos first." >&2
  exit 1
fi

# mirror_files <source-dir> <destination-dir>
# Copies every regular file, recreating the relative directory structure.
mirror_files() {
  local src_dir="$1"
  local dst_dir="$2"
  if [ ! -d "$src_dir" ]; then
    echo "ERROR: missing tracked source directory: $src_dir" >&2
    exit 1
  fi
  while IFS= read -r src; do
    local rel="${src#"$src_dir"/}"
    local dst="$dst_dir/$rel"
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  done < <(find "$src_dir" -type f -print | sort)
  echo "  $src_dir"
  echo "  -> $dst_dir"
}

# mirror_ets_sources
# Copies harmonyos/ets-source/** into entry/src/main/ets/**, skipping the
# resources/ subtree, which belongs to entry/src/main/resources instead.
mirror_ets_sources() {
  local src_dir="$REPO_ROOT/harmonyos/ets-source"
  local dst_dir="$MODULE_ROOT/ets"
  while IFS= read -r src; do
    local rel="${src#"$src_dir"/}"
    case "$rel" in
      resources/*) continue ;;
    esac
    local dst="$dst_dir/$rel"
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  done < <(find "$src_dir" -type f -print | sort)
  echo "  harmonyos/ets-source (code)"
  echo "  -> build/libstellarium-harmonyos/entry/src/main/ets"
}

# mirror_entry <source-relative-path> <destination-relative-path>
# Same as mirror_files but for a single file.
mirror_entry() {
  local src="$REPO_ROOT/$1"
  local dst="$GEN_ROOT/$2"
  if [ ! -f "$src" ]; then
    echo "ERROR: missing tracked source: $src" >&2
    exit 1
  fi
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "  $1"
  echo "  -> $2"
}

echo "Synced:"

# DevEco owns build-profile.json5 and its local signing credentials; never sync it here.

# 1. ArkTS / TypeScript sources (harmonyos/ets-source/resources is handled separately).
mirror_ets_sources

# 2. Icons and locale tables shipped next to the ArkTS sources.
mirror_files "$REPO_ROOT/harmonyos/ets-source/resources" "$MODULE_ROOT/resources"

# 3. Module resources are authoritative for paths they also define.
mirror_files "$REPO_ROOT/harmonyos/resources" "$MODULE_ROOT/resources"

# 4. App scope resources.
# AppScope/app.json5 is deliberately NOT mirrored: bundleName, vendor and
# versionCode are local/publish configuration. Overwriting them would silently
# revert a locally chosen package name and make the generated SigningConfigs
# stop matching ("bundleName does not match the generated SigningConfigs").
mirror_files "$REPO_ROOT/harmonyos/AppScope/resources" "$GEN_ROOT/AppScope/resources"

# 5. Module manifest.
mirror_entry "harmonyos/module.json5" "entry/src/main/module.json5"

# 6. Native template sources.
mirror_entry "harmonyos/cpp-source/hello.cpp" "entry/src/main/cpp/hello.cpp"
mirror_entry "harmonyos/cpp-source/PresentationGeometry.h" "entry/src/main/cpp/PresentationGeometry.h"
mirror_entry "harmonyos/cpp-source/CMakeLists.txt" "entry/src/main/cpp/CMakeLists.txt"
mirror_files "$REPO_ROOT/harmonyos/cpp-source/types/libentry" "$MODULE_ROOT/cpp/types/libentry"

node "$SCRIPT_DIR/configure-ohos-model-worker.mjs"

# The native Stellarium library is produced by the cross-compiled CMake build.
# Keep the generated hvigor project from silently packaging an older .so after
# the C++ source was rebuilt.
NATIVE_SOURCE="$REPO_ROOT/build/src/libstellarium.so"
NATIVE_TARGET="$GEN_ROOT/entry/libs/arm64-v8a/libstellarium.so"
if [ -f "$NATIVE_SOURCE" ]; then
  mkdir -p "$(dirname "$NATIVE_TARGET")"
  cp "$NATIVE_SOURCE" "$NATIVE_TARGET"
  echo "  $NATIVE_SOURCE"
  echo "  -> build/libstellarium-harmonyos/entry/libs/arm64-v8a/libstellarium.so"
else
  echo "WARNING: missing cross-compiled libstellarium.so at $NATIVE_SOURCE; generated HAP may contain an older native library" >&2
fi

OHOS_ADDITIONAL_PKGS="${OHOS_ADDITIONAL_PKGS:-$HOME/.local/opt/ohos/additional-packages}"
JPEG_SOURCE="$OHOS_ADDITIONAL_PKGS/lib/libjpeg.so"
JPEG_TARGET="$GEN_ROOT/entry/libs/arm64-v8a/libjpeg.so"
if [ -f "$JPEG_SOURCE" ]; then
  mkdir -p "$(dirname "$JPEG_TARGET")"
  cp "$JPEG_SOURCE" "$JPEG_TARGET"
  echo "  $JPEG_SOURCE"
  echo "  -> build/libstellarium-harmonyos/entry/libs/arm64-v8a/libjpeg.so"
else
  echo "WARNING: missing HarmonyOS libjpeg.so at $JPEG_SOURCE; JPEG textures will not load" >&2
fi
